spring:
  application:
    name: board
  datasource:
    url: jdbc:mysql://localhost:3306/board?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: ${username}
    password: ${password}
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

server:
  port: 8000