name: Deployment

on:
 push:
    branches: [ "main"]

jobs:
  deployment:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    
    steps:
    - name: executing remote ssh commands using password
       # ssh username@ip
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
         cd ci2
         git pull
         sh gradlew build
         nohup java -jar build/libs/*T.jar & >/dev/null 2>&1 &
      
    
    
    

    # Configure Gradle for optimal use in GiHub Actions, including caching of downloaded dependencies.
    # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0
      
    - name: chmod
      run: chmod 744 gradlew
    - name: Build with Gradle Wrapper
      run: ./gradlew build

   

 
